import { Inter } from "next/font/google";
import "../globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "WITL-HITL",
  description: "Generated by create next app",
};

export default function AppLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="flex min-h-screen">
            <aside className=" w-48 p-8 bg-blue-100">
                aside stuffs
            </aside>
          <div className="p-6 max-w-4xl mx-auto">
          {children}
          </div>
        </main>
       
      </body>
    </html>
  );
}
