import { Inter } from "next/font/google";
import "../globals.css";
import { getServerSession } from "next-auth";
import { authOptions } from "../api/auth/[...nextauth]/route";
import { redirect } from "next/navigation";
import Image from "next/image";
import Link from "next/link";
const inter = Inter({ subsets: ["latin"] });
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import {
  faFileInvoice,
  faRightFromBracket,
} from "@fortawesome/free-solid-svg-icons";
import { faChartLine } from "@fortawesome/free-solid-svg-icons";
import { faArrowLeft } from "@fortawesome/free-solid-svg-icons";
import LogoutButton from "@/components/buttons/LogoutButton";

export const metadata = {
  title: "WITL-HITL",
  description: "Generated by create next app",
};

export default async function AppLayout({ children }) {
  const session = getServerSession(authOptions);
  if (!session) {
    return redirect("/");
  }
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="flex min-h-screen">
          <aside className=" w-48 p-8 bg-white shadow">
            aside stuffs
            <div className="rounded-full overflow-hidden mx-auto">
              <Image
                src={(await session)?.user?.image}
                alt={"avatar"}
                width={126}
                height={128}
              />
            </div>
            <nav className="flex flex-col text-center gap-4 mt-12  text-gray-800">
              <Link href={"/account"} className="flex gap-3 ">
                <FontAwesomeIcon
                  fixedWidth={true}
                  icon={faFileInvoice}
                  className="h-6 w-6"
                />
                <span>My Page</span>
              </Link>
              <Link href={"/analytics"} className="flex gap-3 ">
                <FontAwesomeIcon
                  fixedWidth={true}
                  icon={faChartLine}
                  className="h-6 w-6"
                />
                <span>Analytics</span>
              </Link>
              <LogoutButton
                className="flex gap-3 items-center"
                iconClasses="h-6 w-6"
                iconLeft={true}
              />
              <Link
                href={"/"}
                className="flex items-center gap-2 text-xs text-gray-500 border-t pt-4"
              >
                <FontAwesomeIcon icon={faArrowLeft} className={"w-3 h-3"} />
                <span>Back to website</span>
              </Link>
            </nav>
          </aside>
          <div className="">
            <div className="bg-white m-4 p-4 shadow">{children}</div>
          </div>
        </main>
      </body>
    </html>
  );
}
