
import { Lato } from "next/font/google";
import "../globals.css";
import { getServerSession } from "next-auth";
import { authOptions } from "../api/auth/[...nextauth]/route";
import { redirect } from "next/navigation";
import Image from "next/image";
import AppSideBar from "@/components/layout/AppSideBar";
const lato = Lato({ subsets: ["latin"],weight:['400','700'] });

export const metadata = {
  title: "WITL-HITL",
  description: "Generated by create next app",
};

export default async function AppLayout({ children }) {
  const session = getServerSession(authOptions);
  if (!session) {
    return redirect("/");
  }
  return (
    <html lang="en">
      <body className={lato.className}>
        <main className="flex min-h-screen ">
          <aside className=" w-48 p-4 pt-6 bg-white shadow">
            aside stuffs
            <div className="rounded-full overflow-hidden mx-auto">
              <Image
                src={(await session)?.user?.image}
                alt={"avatar"}
                width={256}
                height={256}
              />
            </div>
            <AppSideBar/>
          </aside>
          <div className="w-full">
            <div className="bg-white m-4 p-4 shadow">{children}</div>
          </div>
        </main>
      </body>
    </html>
  );
}
